In [1]:
import numpy as np
#將上列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")
#呈上題的 array，找出被 6 除餘 1 的數的索引

In [3]:
array1 = np.array(range(30))
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
array1.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [5]:
array1.reshape(5,6,order="F")
######  按列(row)填充應為 order="C"; order="F"為按欄(column)填充

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [6]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
array1.reshape(5,6,order="F")%6

array([[0, 5, 4, 3, 2, 1],
       [1, 0, 5, 4, 3, 2],
       [2, 1, 0, 5, 4, 3],
       [3, 2, 1, 0, 5, 4],
       [4, 3, 2, 1, 0, 5]], dtype=int32)

In [9]:
np.where(array1.reshape(5,6,order="F")%6==1)

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))