作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [1]:
import numpy as np

In [2]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

In [3]:
with open('D06.npz', 'wb') as f:
    np.savez(f, array1, array2)

In [4]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

In [5]:
npzfile = np.load('D06.npz')
type(npzfile)

numpy.lib.npyio.NpzFile

In [6]:
npzfile.files

['arr_0', 'arr_1']

In [7]:
npzfile.files[1]

'arr_1'

In [8]:
npzfile

In [9]:
npzfile['arr_0']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
array3 = np.array([6,7,8])

In [11]:
npzfile[npzfile.files[0]]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
with open('D06-1.npz', 'wb') as f:
    np.savez(f,npzfile[npzfile.files[0]],npzfile[npzfile.files[1]], array3)

In [13]:
npzfile1 = np.load('D06-1.npz')
npzfile1.files

['arr_0', 'arr_1', 'arr_2']

In [16]:
npzfile1.files[0]

'arr_0'

In [17]:
npzfile1['arr_0']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
npzfile1['arr_2']

array([6, 7, 8])